#!/bin/sh

# Get the current branch name
current_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)

if [ $? -eq 0 ]; then
    echo "You are on branch: $current_branch"
    export CI_BRANCH=$current_branch
else
    echo "Not in a Git repository or an error occurred."
fi
